on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.11'
    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - run: pip install poetry==1.8.1
      - uses: actions/checkout@v4
      - run: poetry install --all-extras --no-interaction --no-ansi
      - id: version
        run: |
          version=$(poetry run cz version --project)
          echo "version=$version" >> "$GITHUB_OUTPUT"
