on:
  workflow_call:
    inputs:
      publish-major-tag:
        type: boolean
        required: false
        default: false
    secrets:
      GH_TOKEN:
        required: true

jobs:
  bump:
    runs-on: ubuntu-latest
    concurrency: release
    if: success() && github.ref_name == github.event.repository.default_branch
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install poetry==1.7.0
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - run: poetry install --all-extras --no-interaction --no-ansi
      - run: |
          git config --global user.name "commitizen"
          git config --global user.email "commitizen@blindfolded.surgery"
      - name: Bump version
        id: bump
        run: |
          set +e
          poetry run cz bump
          EXIT_CODE="$?"
          set -e

          case $EXIT_CODE in
          21)
            echo "bumped=false" >> $GITHUB_OUTPUT
            exit 0;;
          0)
            echo "bumped=true" >> $GITHUB_OUTPUT
            ;;
          *)
            exit $EXIT_CODE;;
          esac
          
          version=$(poetry version --short)
          echo "version=$version" >> $GITHUB_OUTPUT
          major_version=$(echo "$version" | cut -d. -f1 -)
          echo "major_version=$major_version" >> $GITHUB_OUTPUT
      - name: Create and push major tag
        if: steps.bump.outputs.bumped == 'true' && inputs.publish-major-tag
        env:
          MAJOR_VERSION: ${{ steps.bump.outputs.major_version }}
        run: |
          git tag --force "v$MAJOR_VERSION"
          git push --force origin "v$MAJOR_VERSION"
      - name: Create PR and exact tag
        if: steps.bump.outputs.bumped == 'true'
        id: pr-create
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ steps.bump.outputs.version }}
        run: |
          git push origin "v$VERSION"
          git switch -c bump-version
          git push origin bump-version
          pr_url=$(gh pr create --title "Bump to $VERSION" --body "Autogenerated PR.")
          echo "pr_url=$pr_url" >> "$GITHUB_OUTPUT"
      - name: Set PR to auto-merge
        if: steps.bump.outputs.bumped == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ steps.pr-create.outputs.pr_url }}
        run: |
          gh pr merge --rebase --auto "$PR_URL"
