on:
  workflow_call:
    inputs:
      build-tool:
        type: string
        default: poetry
      python-version:
        type: string
        default: '3.11'
    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - run: pipx install poetry==1.8.5
        if: inputs.build-tool == 'poetry'
      - name: Install uv
        if: inputs.build-tool == 'uv'
        uses: astral-sh/setup-uv@v5
        with:
          cache-suffix: -actions-releases
          version: 0.5.6
      - uses: actions/checkout@v4
      - run: poetry install --all-extras --no-interaction --no-ansi
        if: inputs.build-tool == 'poetry'
      - run: uv sync
        if: inputs.build-tool == 'uv'
      - id: version
        run: |
          version=$(${{ inputs.build-tool }} run cz version --project)
          echo "version=$version" >> "$GITHUB_OUTPUT"
