on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install poetry==1.7.0
      - uses: actions/checkout@v4
      - run: poetry install --all-extras --no-interaction --no-ansi
      - id: version
        run: |
          version=$(poetry run cz version --project)
          echo "version=$version" >> "$GITHUB_OUTPUT"
