on:
  workflow_call:
    inputs:
      build-tool:
        type: string
        required: false
        default: poetry
      python-version:
        type: string
        default: '3.11'

jobs:
  check:
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - run: pipx install poetry==1.8.5
        if: inputs.build-tool == 'poetry'
      - name: Install uv
        if: inputs.build-tool == 'uv'
        uses: astral-sh/setup-uv@v4
        with:
          version: 0.5.6
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - run: poetry install --all-extras --no-interaction --no-ansi
        if: inputs.build-tool == 'poetry'
      - run: uv sync
        if: inputs.build-tool == 'uv'
      - run: ${{ inputs.build-tool }} run cz check --rev-range origin/main..HEAD
