on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  commitizen:
    uses: ./.github/workflows/commitizen.yml
    with:
      publish-major-tag: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
